'use client'
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppLayout from "@/components/layout/appLayout";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const otherLayoutList = ['/login']
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname()
  return (
    <html lang="en">
      <body className={inter.className}>{
        otherLayoutList.includes(pathname) ? children : <AppLayout>{children}</AppLayout>
      }
        
      </body>
    </html>
  );
}
